[package]
name = "sqlite3"
edition.workspace = true
version.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
keywords.workspace = true

[dependencies]

[features]

[build-dependencies]
cc = "1.0.46"
