name: "Build Android library"
description: "Create artifact for Android library"
inputs:
  sign-publication:
    description: "Whether to sign the built library"
    default: '1'
  gpg-key:
    required: false
    description: "The GPG key to use when signing the publication"
  gpg-password:
    required: false
    description: "Password for the GPG key."

runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v5
      with:
        distribution: "temurin"
        java-version: "25"

    - name: Validate Gradle wrapper
      uses: gradle/actions/wrapper-validation@v4

    - name: Setup
      shell: bash
      run: |
        rustup toolchain install nightly-2025-04-15-x86_64-unknown-linux-gnu
        rustup component add rust-src --toolchain nightly-2025-04-15-x86_64-unknown-linux-gnu
        rustup target add \
          aarch64-linux-android \
          armv7-linux-androideabi \
          x86_64-linux-android \
          i686-linux-android
        cargo install cargo-ndk
    
    - name: Build signed library
      shell: bash
      if: ${{ inputs.sign-publication == '1' }}
      run: |
        cd android
        ./gradlew build zipPublication  -PgpgKey=${{ inputs.gpg-key }} -PgpgPassword=${{ inputs.gpg-password }}
        ls -lh build/outputs/aar
        find build/repository

    - name: Build library without signing
      shell: bash
      if: ${{ inputs.sign-publication == '0' }}
      run: |
        cd android
        ./gradlew build zipPublication -PsignPublication=0
        ls -lh build/outputs/aar
        find build/repository

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: android-library
        retention-days: 14
        compression-level: 0 # We're uploading a zip, no need to compress again
        path: android/build/distributions/powersync_android.zip
        if-no-files-found: error

    - name: Copy static libraries
      shell: bash
      run: |
        cp target/aarch64-linux-android/release/libpowersync.a libpowersync_aarch64.android.a
        cp target/aarch64-linux-android/release/libpowersync.so libpowersync_aarch64.android.so

        cp target/armv7-linux-androideabi/release/libpowersync.a libpowersync_armv7.android.a
        cp target/armv7-linux-androideabi/release/libpowersync.so libpowersync_armv7.android.so

        cp target/i686-linux-android/release/libpowersync.a libpowersync_x86.android.a
        cp target/i686-linux-android/release/libpowersync.so libpowersync_x86.android.so

        cp target/x86_64-linux-android/release/libpowersync.a libpowersync_x64.android.a
        cp target/x86_64-linux-android/release/libpowersync.so libpowersync_x64.android.so

    - name: Upload static libraries
      uses: actions/upload-artifact@v4
      with:
        name: android-static
        retention-days: 14
        path: |
          *.a
          *.so
