name: "Build Android library"
description: "Create artifact for Android library"
inputs:
  gpg-key:
    required: false
    description: "The GPG key to use when signing the publication"
  gpg-password:
    required: false
    description: "Password for the GPG key."

runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: "17"

    - name: Validate Gradle wrapper
      uses: gradle/actions/wrapper-validation@v4

    - name: Setup
      shell: bash
      run: |
        rustup toolchain install nightly-2025-04-15-x86_64-unknown-linux-gnu
        rustup component add rust-src --toolchain nightly-2025-04-15-x86_64-unknown-linux-gnu
        rustup target add \
          aarch64-linux-android \
          armv7-linux-androideabi \
          x86_64-linux-android \
          i686-linux-android
        cargo install cargo-ndk
    
    - name: Build for Android
      shell: bash
      env:
        GPG_PRIVATE_KEY: ${{ inputs.gpg-key }}
        GPG_PASSWORD: ${{ inputs.gpg-password }}
      run: |
        cd android
        ./gradlew build publishAllPublicationsToHereRepository
        ls -lh build/outputs/aar
        find build/repository

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: android-library
        retention-days: 1
        compression-level: 0 # We're uploading a zip, no need to compress again
        path: android/build/distributions/powersync_android.zip
        if-no-files-found: error
