on:
  push:
  pull_request:
name: "android"
jobs:
  build:
    name: Building Android
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build Android
        uses: ./.github/actions/android
        with:
          sign-publication: '1'
          gpg-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-password: ${{ secrets.GPG_PASSWORD }}

  test_release:
    needs: [build]
    runs-on: ubuntu-latest
    name: Releasing Android for test
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository)
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v4
        with:
          name: android-library

      - name: Publish to Maven Central
        run: |
          ls -al
          curl --request POST \
            --header 'Authorization: Bearer ${{ secrets.CENTRAL_AUTH }}' \
            --form bundle=@powersync_android.zip \
            https://central.sonatype.com/api/v1/publisher/upload
