on:
  push:
  pull_request:
name: "android"
jobs:
  build:
    name: Building Android
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build Android
        uses: ./.github/actions/android
        with:
          sign-publication: '0'

  test_release:
    needs: [build]
    name: Building Android
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository)
    steps:
      - name: Publish to Maven Central
        run: |
          curl --request POST \
            --header 'Authorization: Bearer ${{ secrets.CENTRAL_AUTH }}' \
            --form bundle=@powersync-android.zip \
            https://central.sonatype.com/api/v1/publisher/upload
