on:
  push:
  pull_request:
name: "valgrind"
jobs:
  build:
    name: Testing with Valgrind on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository)
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install valgrind
        run: sudo apt update && sudo apt install -y valgrind

      - name: Install Cargo Valgrind
        run: |
          cargo install cargo-valgrind

      - name: Test Core
        run: |
          cargo valgrind test -p powersync_core --features loadable_extension
